# nixpacks.toml
[phases.setup]
nixpkgs = ["nodejs_22", "yarn"]

[phases.install]
dependsOn = ["setup"]
cmds = ["yarn install --frozen-lockfile"]

[phases.build]
dependsOn = ["install"]
cmds = ["yarn build:web", "npm install -g serve"]

[start]
cmd = "serve -s apps/web/dist -p $PORT"
