# nixpacks.toml
[phases.setup]
nixpkgs = ["nodejs_22"]

[phases.install]
dependsOn = ["setup"]
cmds = ["npm ci --workspace=web --include-workspace-root"]

[phases.build]
dependsOn = ["install"]
cmds = ["npm run build:web"]

[start]
cmd = "npx serve -s apps/web/dist -p $PORT"
