[phases.setup]
nixpkgs = ["nodejs_22", "yarn"]

[phases.install]
dependsOn = ["setup"]
cmds = [
  "git fetch origin main",
  "git reset --hard origin/main",
  "yarn install --frozen-lockfile"
]

[phases.build]
dependsOn = ["install"]

cmds = ["yarn build:web"]

[start]

cmd = ["npx", "serve", "-s", "apps/web/dist", "-l", "4000"]
